spring.application.name=gateaway-service
server.port = 8080

spring.datasource.url = jdbc:postgresql://localhost:5432/gateway_db
spring.datasource.username = postgres
spring.datasource.password = password

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

spring.redis.host = localhost
spring.redis.port = 6379